import type { TemplateData } from '../core/plan.js'

/**
 * Generates PocketBase auth configuration as strings (snapshot-tested).
 *
 * Static method flags (password/OTP/MFA) go in a migration — they are part of
 * the schema's history. OAuth providers are synced from environment secrets
 * in an onBootstrap hook instead: migrations run once, but secrets are
 * typically added in the PocketHost dashboard AFTER the first deploy, and a
 * hook picks them up on the next restart with no migration re-run.
 */

export const AUTH_MIGRATION_FILENAME =
  'pb_migrations/1700000001_configure_auth.js'
export const OAUTH_HOOK_FILENAME = 'pb_hooks/oauth.pb.js'

export function generateAuthMigration(auth: TemplateData['auth']): string {
  return `/// <reference path="../pb_data/types.d.ts" />

// Generated by ph create — enables the selected auth methods on the users
// collection. OAuth2 providers are configured separately in pb_hooks/oauth.pb.js.
migrate(
  (app) => {
    const users = app.findCollectionByNameOrId('users')
    users.passwordAuth.enabled = ${auth.password}
    users.otp.enabled = ${auth.otp}
    users.mfa.enabled = ${auth.mfa}
    app.save(users)
  },
  (app) => {
    const users = app.findCollectionByNameOrId('users')
    users.passwordAuth.enabled = true
    users.otp.enabled = false
    users.mfa.enabled = false
    app.save(users)
  },
)
`
}

export function generateOAuthHook(providers: readonly string[]): string {
  const wanted = providers
    .map((provider) => {
      const upper = provider.toUpperCase()
      return `  { name: '${provider}', idVar: '${upper}_CLIENT_ID', secretVar: '${upper}_CLIENT_SECRET' },`
    })
    .join('\n')

  return `/// <reference path="../pb_data/types.d.ts" />

// Generated by ph create — syncs OAuth2 providers from environment secrets on
// every startup. Add <PROVIDER>_CLIENT_ID / <PROVIDER>_CLIENT_SECRET in the
// PocketHost dashboard (Secrets) and restart the instance to activate.
onBootstrap((e) => {
  e.next()

  const wanted = [
${wanted}
  ]

  const users = e.app.findCollectionByNameOrId('users')
  const providers = []
  for (const entry of wanted) {
    const clientId = $os.getenv(entry.idVar)
    const clientSecret = $os.getenv(entry.secretVar)
    if (clientId && clientSecret) {
      providers.push({ name: entry.name, clientId: clientId, clientSecret: clientSecret })
    } else {
      console.log(
        '[oauth] ' +
          entry.name +
          ' not configured — set ' +
          entry.idVar +
          ' and ' +
          entry.secretVar +
          ' in PocketHost secrets',
      )
    }
  }

  users.oauth2.enabled = providers.length > 0
  users.oauth2.providers = providers
  e.app.save(users)
})
`
}
